INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:34:20] "[32mGET / HTTP/1.1[0m" 302 -
ERROR D:\anaconda\envs\network\lib\site-packages\flask\app.py:1891 Exception on /login [GET]
Traceback (most recent call last):
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\envs\network\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python\disinfection_car_website\controller\modules\user\views.py", line 14, in login
    return render_template("login.html")
  File "D:\anaconda\envs\network\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "D:\anaconda\envs\network\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "D:\anaconda\envs\network\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "D:\anaconda\envs\network\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "D:\anaconda\envs\network\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "D:\anaconda\envs\network\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "D:\anaconda\envs\network\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login.html
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:34:20] "[35m[1mGET /login HTTP/1.1[0m" 500 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:34:21] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:04] "[32mGET / HTTP/1.1[0m" 302 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:04] "[37mGET /login HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:04] "[37mGET /static/css/style.css HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:04] "[37mGET /static/images/avtar.png HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:04] "[37mGET /static/images/bg1.jpg HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:04] "[37mGET /static/images/close.png HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:04] "[37mGET /static/images/adm.png HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:04] "[37mGET /static/images/pass.png HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:04] "[37mGET /static/images/key.png HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:10] "[37mPOST /login HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:15] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:15] "[37mGET / HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:15] "[37mGET /static/recorder.js HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:15] "[35m[1mGET /video_viewer HTTP/1.1[0m" 500 -
ERROR D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 Error on request:
Traceback (most recent call last):
  File "D:\anaconda\envs\network\Lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "D:\anaconda\envs\network\Lib\site-packages\werkzeug\serving.py", line 314, in execute
    for data in application_iter:
  File "D:\anaconda\envs\network\Lib\site-packages\werkzeug\wsgi.py", line 506, in __next__
    return self._next()
  File "D:\anaconda\envs\network\Lib\site-packages\werkzeug\wrappers\base_response.py", line 45, in _iter_encoded
    for item in iterable:
  File "D:\python\disinfection_car_website\controller\modules\home\views.py", line 35, in video_stream
    video_camera = VideoCamera()
NameError: name 'VideoCamera' is not defined
ERROR D:\anaconda\envs\network\lib\site-packages\flask\app.py:1891 Exception on /record_status [POST]
Traceback (most recent call last):
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\envs\network\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python\disinfection_car_website\controller\modules\user\views.py", line 45, in record_status
    if video_camera is None:
NameError: name 'video_camera' is not defined
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:30] "[35m[1mPOST /record_status HTTP/1.1[0m" 500 -
ERROR D:\anaconda\envs\network\lib\site-packages\flask\app.py:1891 Exception on /record_status [POST]
Traceback (most recent call last):
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\envs\network\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python\disinfection_car_website\controller\modules\user\views.py", line 45, in record_status
    if video_camera is None:
NameError: name 'video_camera' is not defined
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:31] "[35m[1mPOST /record_status HTTP/1.1[0m" 500 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:14:37] "[37mGET / HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:14:40] "[37mGET /video_viewer HTTP/1.1[0m" 200 -
ERROR D:\anaconda\envs\network\lib\site-packages\flask\app.py:1891 Exception on /record_status [POST]
Traceback (most recent call last):
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\envs\network\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python\disinfection_car_website\controller\modules\user\views.py", line 45, in record_status
    if video_camera is None:
NameError: name 'video_camera' is not defined
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:14:48] "[35m[1mPOST /record_status HTTP/1.1[0m" 500 -
ERROR D:\anaconda\envs\network\lib\site-packages\flask\app.py:1891 Exception on /record_status [POST]
Traceback (most recent call last):
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\envs\network\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python\disinfection_car_website\controller\modules\user\views.py", line 45, in record_status
    if video_camera is None:
NameError: name 'video_camera' is not defined
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:14:59] "[35m[1mPOST /record_status HTTP/1.1[0m" 500 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:25:21] "[32mGET / HTTP/1.1[0m" 302 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:25:21] "[37mGET /login HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:25:22] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:25:24] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:25:24] "[37mGET / HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:25:26] "[37mGET /video_viewer HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:25:30] "[37mPOST /record_status HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:25:43] "[37mPOST /record_status HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:26:01] "[33mGET /static/video.avi HTTP/1.1[0m" 404 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:26:11] "[37mGET /video_viewer HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:26:14] "[37mGET / HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:26:14] "[37mGET /video_viewer HTTP/1.1[0m" 200 -
