INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:34:20] "[32mGET / HTTP/1.1[0m" 302 -
ERROR D:\anaconda\envs\network\lib\site-packages\flask\app.py:1891 Exception on /login [GET]
Traceback (most recent call last):
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\envs\network\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python\disinfection_car_website\controller\modules\user\views.py", line 14, in login
    return render_template("login.html")
  File "D:\anaconda\envs\network\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "D:\anaconda\envs\network\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "D:\anaconda\envs\network\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "D:\anaconda\envs\network\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "D:\anaconda\envs\network\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "D:\anaconda\envs\network\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "D:\anaconda\envs\network\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login.html
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:34:20] "[35m[1mGET /login HTTP/1.1[0m" 500 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:34:21] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:04] "[32mGET / HTTP/1.1[0m" 302 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:04] "[37mGET /login HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:04] "[37mGET /static/css/style.css HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:04] "[37mGET /static/images/avtar.png HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:04] "[37mGET /static/images/bg1.jpg HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:04] "[37mGET /static/images/close.png HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:04] "[37mGET /static/images/adm.png HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:04] "[37mGET /static/images/pass.png HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:04] "[37mGET /static/images/key.png HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:10] "[37mPOST /login HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:15] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:15] "[37mGET / HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:15] "[37mGET /static/recorder.js HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:15] "[35m[1mGET /video_viewer HTTP/1.1[0m" 500 -
ERROR D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 Error on request:
Traceback (most recent call last):
  File "D:\anaconda\envs\network\Lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "D:\anaconda\envs\network\Lib\site-packages\werkzeug\serving.py", line 314, in execute
    for data in application_iter:
  File "D:\anaconda\envs\network\Lib\site-packages\werkzeug\wsgi.py", line 506, in __next__
    return self._next()
  File "D:\anaconda\envs\network\Lib\site-packages\werkzeug\wrappers\base_response.py", line 45, in _iter_encoded
    for item in iterable:
  File "D:\python\disinfection_car_website\controller\modules\home\views.py", line 35, in video_stream
    video_camera = VideoCamera()
NameError: name 'VideoCamera' is not defined
ERROR D:\anaconda\envs\network\lib\site-packages\flask\app.py:1891 Exception on /record_status [POST]
Traceback (most recent call last):
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\envs\network\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python\disinfection_car_website\controller\modules\user\views.py", line 45, in record_status
    if video_camera is None:
NameError: name 'video_camera' is not defined
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:30] "[35m[1mPOST /record_status HTTP/1.1[0m" 500 -
ERROR D:\anaconda\envs\network\lib\site-packages\flask\app.py:1891 Exception on /record_status [POST]
Traceback (most recent call last):
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\envs\network\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python\disinfection_car_website\controller\modules\user\views.py", line 45, in record_status
    if video_camera is None:
NameError: name 'video_camera' is not defined
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 11:36:31] "[35m[1mPOST /record_status HTTP/1.1[0m" 500 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:14:37] "[37mGET / HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:14:40] "[37mGET /video_viewer HTTP/1.1[0m" 200 -
ERROR D:\anaconda\envs\network\lib\site-packages\flask\app.py:1891 Exception on /record_status [POST]
Traceback (most recent call last):
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\envs\network\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python\disinfection_car_website\controller\modules\user\views.py", line 45, in record_status
    if video_camera is None:
NameError: name 'video_camera' is not defined
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:14:48] "[35m[1mPOST /record_status HTTP/1.1[0m" 500 -
ERROR D:\anaconda\envs\network\lib\site-packages\flask\app.py:1891 Exception on /record_status [POST]
Traceback (most recent call last):
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\envs\network\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python\disinfection_car_website\controller\modules\user\views.py", line 45, in record_status
    if video_camera is None:
NameError: name 'video_camera' is not defined
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:14:59] "[35m[1mPOST /record_status HTTP/1.1[0m" 500 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:25:21] "[32mGET / HTTP/1.1[0m" 302 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:25:21] "[37mGET /login HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:25:22] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:25:24] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:25:24] "[37mGET / HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:25:26] "[37mGET /video_viewer HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:25:30] "[37mPOST /record_status HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:25:43] "[37mPOST /record_status HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:26:01] "[33mGET /static/video.avi HTTP/1.1[0m" 404 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:26:11] "[37mGET /video_viewer HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:26:14] "[37mGET / HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:26:14] "[37mGET /video_viewer HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:41:17] "[37mGET / HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:41:18] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
ERROR D:\anaconda\envs\network\lib\site-packages\flask\app.py:1891 Exception on /disinfection_car/login [GET]
Traceback (most recent call last):
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\envs\network\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python\disinfection_car_website\app.py", line 46, in login
    return render_template("login.html")
  File "D:\anaconda\envs\network\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "D:\anaconda\envs\network\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "D:\anaconda\envs\network\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "D:\anaconda\envs\network\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "D:\anaconda\envs\network\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\python\disinfection_car_website\templates\login.html", line 44, in top-level template code
    <form method="post" action="{{ url_for("user.login") }}">
  File "D:\anaconda\envs\network\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\envs\network\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\envs\network\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "D:\anaconda\envs\network\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user.login'. Did you mean 'login' instead?
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:41:31] "[35m[1mGET /disinfection_car/login HTTP/1.1[0m" 500 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:43:14] "[37mGET / HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:43:16] "[37mGET /disinfection_car/login HTTP/1.1[0m" 200 -
ERROR D:\anaconda\envs\network\lib\site-packages\flask\app.py:1891 Exception on /disinfection_car/login [POST]
Traceback (most recent call last):
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\envs\network\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python\disinfection_car_website\app.py", line 58, in login
    return redirect(url_for("home.index"))
  File "D:\anaconda\envs\network\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\envs\network\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\envs\network\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "D:\anaconda\envs\network\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'home.index'. Did you mean 'index' instead?
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:43:18] "[35m[1mPOST /disinfection_car/login HTTP/1.1[0m" 500 -
ERROR D:\anaconda\envs\network\lib\site-packages\flask\app.py:1891 Exception on /disinfection_car/login [POST]
Traceback (most recent call last):
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\envs\network\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python\disinfection_car_website\app.py", line 43, in login
    return redirect(url_for("home.index"))
  File "D:\anaconda\envs\network\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "D:\anaconda\envs\network\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\envs\network\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\envs\network\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "D:\anaconda\envs\network\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'home.index'. Did you mean 'index' instead?
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:44:46] "[35m[1mPOST /disinfection_car/login HTTP/1.1[0m" 500 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:45:18] "[37mGET / HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:45:21] "[32mGET /disinfection_car/login HTTP/1.1[0m" 302 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:45:21] "[37mGET /disinfection_car/home HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:45:24] "[37mGET /disinfection_car/video_viewer HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:45:26] "[33mPOST /record_status HTTP/1.1[0m" 404 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:45:34] "[33mPOST /record_status HTTP/1.1[0m" 404 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:46:50] "[32mGET /disinfection_car/logout HTTP/1.1[0m" 302 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [14/Mar/2021 15:46:50] "[37mGET /disinfection_car/login HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [15/Mar/2021 00:17:31] "[37mGET / HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [15/Mar/2021 00:17:31] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [15/Mar/2021 00:18:03] "[32mGET /disinfection_car/home HTTP/1.1[0m" 302 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [15/Mar/2021 00:18:03] "[37mGET /disinfection_car/login HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [15/Mar/2021 00:18:03] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [15/Mar/2021 00:18:03] "[36mGET /static/images/avtar.png HTTP/1.1[0m" 304 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [15/Mar/2021 00:18:03] "[36mGET /static/images/bg1.jpg HTTP/1.1[0m" 304 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [15/Mar/2021 00:18:03] "[36mGET /static/images/close.png HTTP/1.1[0m" 304 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [15/Mar/2021 00:18:03] "[36mGET /static/images/adm.png HTTP/1.1[0m" 304 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [15/Mar/2021 00:18:03] "[36mGET /static/images/pass.png HTTP/1.1[0m" 304 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [15/Mar/2021 00:18:03] "[36mGET /static/images/key.png HTTP/1.1[0m" 304 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [15/Mar/2021 00:18:05] "[32mPOST /disinfection_car/login HTTP/1.1[0m" 302 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [15/Mar/2021 00:18:05] "[37mGET /disinfection_car/home HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [15/Mar/2021 00:18:05] "[37mGET /static/recorder.js HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [15/Mar/2021 00:18:08] "[37mGET /disinfection_car/video_viewer HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [15/Mar/2021 00:18:19] "[37mPOST /disinfection_car/record_status HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [15/Mar/2021 00:18:32] "[37mPOST /disinfection_car/record_status HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [15/Mar/2021 00:18:38] "[37mGET /static/video.avi HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [15/Mar/2021 00:18:41] "[37mGET /static/video.avi HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [15/Mar/2021 00:19:19] "[37mGET /disinfection_car/home HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [15/Mar/2021 00:19:19] "[37mGET /disinfection_car/video_viewer HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 20:57:51] "[37mGET / HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 20:57:52] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 20:57:58] "[37mGET /disinfection_car/login HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 20:57:58] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 20:57:58] "[36mGET /static/images/avtar.png HTTP/1.1[0m" 304 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 20:57:58] "[36mGET /static/images/adm.png HTTP/1.1[0m" 304 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 20:57:58] "[36mGET /static/images/bg1.jpg HTTP/1.1[0m" 304 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 20:57:58] "[36mGET /static/images/close.png HTTP/1.1[0m" 304 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 20:57:58] "[36mGET /static/images/pass.png HTTP/1.1[0m" 304 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 20:57:58] "[36mGET /static/images/key.png HTTP/1.1[0m" 304 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 20:58:01] "[32mPOST /disinfection_car/login HTTP/1.1[0m" 302 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 20:58:01] "[37mGET /disinfection_car/home HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 20:58:03] "[37mGET /disinfection_car/video_viewer HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 21:10:55] "[37mGET / HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 21:10:55] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 21:11:02] "[37mGET /disinfection_car/login HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 21:11:02] "[37mGET /static/css/style.css HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 21:11:02] "[37mGET /static/images/avtar.png HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 21:11:03] "[37mGET /static/images/bg1.jpg HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 21:11:03] "[37mGET /static/images/close.png HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 21:11:03] "[37mGET /static/images/adm.png HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 21:11:03] "[37mGET /static/images/pass.png HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 21:11:03] "[37mGET /static/images/key.png HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 21:11:04] "[32mPOST /disinfection_car/login HTTP/1.1[0m" 302 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 21:11:04] "[37mGET /disinfection_car/home HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 21:11:06] "[37mGET /disinfection_car/video_viewer HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 21:12:16] "[37mGET /disinfection_car/home HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 21:12:18] "[37mGET /disinfection_car/video_viewer HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 21:15:38] "[37mGET /disinfection_car/home HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 21:15:41] "[35m[1mGET /disinfection_car/video_viewer HTTP/1.1[0m" 500 -
ERROR D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 Error on request:
Traceback (most recent call last):
  File "D:\anaconda\envs\network\Lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "D:\anaconda\envs\network\Lib\site-packages\werkzeug\serving.py", line 314, in execute
    for data in application_iter:
  File "D:\anaconda\envs\network\Lib\site-packages\werkzeug\wsgi.py", line 506, in __next__
    return self._next()
  File "D:\anaconda\envs\network\Lib\site-packages\werkzeug\wrappers\base_response.py", line 45, in _iter_encoded
    for item in iterable:
  File "D:\python\disinfection_car_website\app.py", line 99, in video_stream
    frame = video_camera.get_inferred_frame()
TypeError: get_inferred_frame() missing 2 required positional arguments: 'output_video_name' and 'conf_thresh'
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 21:17:32] "[37mGET /disinfection_car/home HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 21:17:40] "[37mGET /disinfection_car/video_viewer HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 21:21:32] "[37mGET /disinfection_car/home HTTP/1.1[0m" 200 -
INFO D:\anaconda\envs\network\lib\site-packages\werkzeug\_internal.py:113 127.0.0.1 - - [17/Mar/2021 21:21:39] "[37mGET /disinfection_car/video_viewer HTTP/1.1[0m" 200 -
